### ISSUE TITLE
i am get error

### ISSUE THREAD

**Issue by MrNodeJS** [akx/walletool#15]
kali@kali:~/Desktop/walletool-master$ python wt_extract_keys.py -d wallet.dat -v 0

Traceback (most recent call last):
  File "wt_extract_keys.py", line 3, in <module>
    from walletool.wallet_items import parse_wallet_dict, KeyWalletItem
  File "/home/kali/Desktop/walletool-master/walletool/wallet_items.py", line 5, in <module>
    from walletool.bc_data_stream import BCDataStream
  File "/home/kali/Desktop/walletool-master/walletool/bc_data_stream.py", line 4, in <module>
    assert sys.version_info[0] == 3  # TODO: Use six for 2/3 compat
AssertionError

Why not work?

**Comment by akx** [comment]
You're using Python 2; that's unsupported.
