### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by moynul6206** [akx/walletool#25]
Traceback (most recent call last):
  File "/home/kali/walletool/wt_extract_keys.py", line 31, in <module>
    main()
  File "/home/kali/walletool/wt_extract_keys.py", line 19, in main
    w_data = read_wallet_dat(args.filename)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/walletool/walletool/wallet_files.py", line 7, in read_wallet_dat
    from bsddb3 import db
ModuleNotFoundError: No module named 'bsddb3'

please give solution

**Comment by tmaljay** [comment]
pip insatll bsddb3 or download its whl file and pip install
